org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties(只支持 26.2)
minecraft_version=26.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.1.0
maven_group=mod.deepseek

# Dependencies
fabric_api_version=0.157.0+26.2
